version: '3.4'
services:
  graylog:
    image: graylog/graylog:2.4.6-1
    ports:
      - '9000:9000'
      - '12201:12201/udp'
      - '514:514'
      - '5555:5555'
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://localhost:9000/api
    depends_on:
      - elasticsearch
      - mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx4g
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true

  mongo:
    image: mongo:3

  mariadb:
    image: mariadb/server:10.4
    ports:
      - '4306:3306'
    volumes:
      - ../docker_volume/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
