spring:
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    url: "jdbc:mariadb://localhost:3306/blog"
    driverClassName: org.mariadb.jdbc.Driver
    username: blog_user
    password: ${BLOG_PASSWD}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        jdbc:
          time_zone: "America/New_York"

server:
  servlet:
    context-path: /
  error:
    include-message: always
  max-http-header-size: 32KB
  port: 6060

springdoc:
  swagger-ui:
    disable-swagger-default-url: true